[package]
name = "speculare-server"
version = "0.1.1"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
r2d2 = "0.8.9"
dotenv = "0.15.0"
futures = "0.3.8"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
openssl = { version = "0.10", features = ["vendored"] }
actix-web = { version = "3.2", features = ["openssl"] }
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
