[package]
name = "speculare-server"
version = "0.1.1"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5"
actix-web-httpauth = "0.5"
actix-web = { version = "3", features = ["openssl"] }
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15"
env_logger = "0.8"
lazy_static = "1.4"
log = "0.4"
openssl = { version = "0.10" }
r2d2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
snmalloc-rs = "0.2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1